import { Geist, Geist_Mono, Lora } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { roboto } from "./fonts";

const lora = Lora({
  subsets: ['latin'],
  variable: '--font-lora',
  display: 'swap',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap"
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Next Js",
    template: "%s | Next Js"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${lora.variable} ${geistSans.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased`}>
        <ul className="gap-3 flex">
          <li>
            <Link href={"/"} >Home</Link>
          </li>
          <li>
            <Link href={"/about"} className="mx-auto">About</Link>
          </li>
          <li>
            <Link href={"/blog"}>Blog</Link>
          </li>
        </ul>
        {children}
      </body>
    </html>
  );
}
